# Generated by Django 5.1.15 on 2026-09-10 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=50)),
                ('block_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('area_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plot_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed')], default='residential', max_length=20)),
                ('facing', models.CharField(blank=True, choices=[('east', 'East'), ('west', 'West'), ('north', 'North'), ('south', 'South'), ('corner', 'Corner')], max_length=20, null=True)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20)),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('floor_level', models.IntegerField(blank=True, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'plot_number')},
            },
        ),
    ]
