# Generated by Django 5.1.15 on 2026-09-10 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_primary', models.CharField(db_index=True, max_length=20)),
                ('phone_alternate', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('walkin', 'Walk-in'), ('website', 'Website'), ('other', 'Other')], max_length=50)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_size_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('site_visit_done', 'Site Visit Done'), ('negotiation', 'Negotiation'), ('booked', 'Booked'), ('deal_confirmed', 'Deal Confirmed'), ('lost', 'Lost')], default='new', max_length=50)),
                ('temperature', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('unqualified', 'Unqualified')], default='unqualified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_callback_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('interested_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('connected', 'Connected'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('switched_off', 'Switched Off'), ('wrong_number', 'Wrong Number'), ('callback_scheduled', 'Callback Scheduled'), ('not_interested', 'Not Interested')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('callback_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_attempts', to='leads.lead')),
            ],
        ),
    ]
